{
  "formatVersion": "1.1",
  "component": {
    "group": "github.ryuunoakaihitomi.retoast",
    "module": "retoast",
    "version": "1.2.3",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "6.5",
      "buildId": "pdl647slzvbshbkh7dqkoea3y4"
    }
  },
  "variants": [
    {
      "name": "releaseApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "retoast-1.2.3.aar",
          "url": "retoast-1.2.3.aar",
          "size": 6290,
          "sha512": "a6ed809af0ea296cefc5a84f166d731a286222a027b6031e91c21f7fb30005c9f8401c0f00c2927763610b40012d98d80994442254841c56064c98986cbcf40f",
          "sha256": "fa916280f30372db40371d61ff23a50dd53d30d5ac4de734232720ad64d2d890",
          "sha1": "23dfab4aaafc5e0cb86dac6fb53cd3a51158ad2d",
          "md5": "71f35eee41fa95b1deef5f967a2cab6f"
        }
      ]
    },
    {
      "name": "releaseRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "retoast-1.2.3.aar",
          "url": "retoast-1.2.3.aar",
          "size": 6290,
          "sha512": "a6ed809af0ea296cefc5a84f166d731a286222a027b6031e91c21f7fb30005c9f8401c0f00c2927763610b40012d98d80994442254841c56064c98986cbcf40f",
          "sha256": "fa916280f30372db40371d61ff23a50dd53d30d5ac4de734232720ad64d2d890",
          "sha1": "23dfab4aaafc5e0cb86dac6fb53cd3a51158ad2d",
          "md5": "71f35eee41fa95b1deef5f967a2cab6f"
        }
      ]
    }
  ]
}
