{
  "formatVersion": "1.1",
  "component": {
    "group": "github.ryuunoakaihitomi.retoast",
    "module": "retoast",
    "version": "1.5.0",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "6.7.1",
      "buildId": "khq3beysvfdxzlgkpavetflynm"
    }
  },
  "variants": [
    {
      "name": "releaseApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "retoast-1.5.0.aar",
          "url": "retoast-1.5.0.aar",
          "size": 6265,
          "sha512": "53ec6fd05ed174646d08bb6c7aee3521e4b7ed7d95b5ce6fd3f5fe755678e1e7b6dd0ae878f23ed458113bc5b0597b4b9700d83f1ab65622d306132cbe7bf8ba",
          "sha256": "c813c1a6c166179baa383e125c39f762f7e6c7ab83eb17a8d152290017a8d889",
          "sha1": "7eaf7c8c3ab4fc62152fdc069d1ea011ef5968ee",
          "md5": "35f314bbfe92ab6638bc873592d81e44"
        }
      ]
    },
    {
      "name": "releaseRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "retoast-1.5.0.aar",
          "url": "retoast-1.5.0.aar",
          "size": 6265,
          "sha512": "53ec6fd05ed174646d08bb6c7aee3521e4b7ed7d95b5ce6fd3f5fe755678e1e7b6dd0ae878f23ed458113bc5b0597b4b9700d83f1ab65622d306132cbe7bf8ba",
          "sha256": "c813c1a6c166179baa383e125c39f762f7e6c7ab83eb17a8d152290017a8d889",
          "sha1": "7eaf7c8c3ab4fc62152fdc069d1ea011ef5968ee",
          "md5": "35f314bbfe92ab6638bc873592d81e44"
        }
      ]
    }
  ]
}
