{
  "formatVersion": "1.1",
  "component": {
    "group": "github.ryuunoakaihitomi.poweract",
    "module": "poweract",
    "version": "1.5.2",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.0.2"
    }
  },
  "variants": [
    {
      "name": "releaseApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "poweract-1.5.2.aar",
          "url": "poweract-1.5.2.aar",
          "size": 51580,
          "sha512": "031664bd0771b9bb77a26db7cf95833e996cf9bc4c8758940de3ff1ce82eb260aec137577ff5422c5ef34b93738b5e70abecfee1953436717e6b64a12807416e",
          "sha256": "56ab3946137e8a358cc0cf0ddce304737b6586a7b6840317fe1c0bf89392b9f3",
          "sha1": "6ad17d877423be23686e5c998f738410f4256ad5",
          "md5": "923b7e7e808936e308db7ecdefcbfd2e"
        }
      ]
    },
    {
      "name": "releaseRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "poweract-1.5.2.aar",
          "url": "poweract-1.5.2.aar",
          "size": 51580,
          "sha512": "031664bd0771b9bb77a26db7cf95833e996cf9bc4c8758940de3ff1ce82eb260aec137577ff5422c5ef34b93738b5e70abecfee1953436717e6b64a12807416e",
          "sha256": "56ab3946137e8a358cc0cf0ddce304737b6586a7b6840317fe1c0bf89392b9f3",
          "sha1": "6ad17d877423be23686e5c998f738410f4256ad5",
          "md5": "923b7e7e808936e308db7ecdefcbfd2e"
        }
      ]
    }
  ]
}
