{
  "formatVersion": "1.1",
  "component": {
    "group": "github.ryuunoakaihitomi.poweract",
    "module": "poweract",
    "version": "1.4.0",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "6.5",
      "buildId": "67dzt5cxgfelhddyyalvef66ji"
    }
  },
  "variants": [
    {
      "name": "releaseApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "poweract-1.4.0.aar",
          "url": "poweract-1.4.0.aar",
          "size": 53719,
          "sha512": "85c1eb34f4149f41edf73df7afb7856af928450b9f2f589676eb540a33905d37674fa860eebd5b88fb063888abc180c9e7a5ec1b39ee5bb89bf75a06e3b6907c",
          "sha256": "a5fa3d8dd012ff6e4ce614b93c61af45c6eb98d6f54a0c7d602cc04559bc0b34",
          "sha1": "dea3af90a2b6b442f67684810b00dd12ab74cc15",
          "md5": "7ef8987179bb12207b9361f6001202e1"
        }
      ]
    },
    {
      "name": "releaseRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "poweract-1.4.0.aar",
          "url": "poweract-1.4.0.aar",
          "size": 53719,
          "sha512": "85c1eb34f4149f41edf73df7afb7856af928450b9f2f589676eb540a33905d37674fa860eebd5b88fb063888abc180c9e7a5ec1b39ee5bb89bf75a06e3b6907c",
          "sha256": "a5fa3d8dd012ff6e4ce614b93c61af45c6eb98d6f54a0c7d602cc04559bc0b34",
          "sha1": "dea3af90a2b6b442f67684810b00dd12ab74cc15",
          "md5": "7ef8987179bb12207b9361f6001202e1"
        }
      ]
    }
  ]
}
