{
  "formatVersion": "1.1",
  "component": {
    "group": "github.ryuunoakaihitomi.retoast",
    "module": "retoast",
    "version": "1.6.3",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "6.7.1",
      "buildId": "r6fl5hkc2bcxjdhtfxqd2suruy"
    }
  },
  "variants": [
    {
      "name": "releaseApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "retoast-1.6.3.aar",
          "url": "retoast-1.6.3.aar",
          "size": 15264,
          "sha512": "804aa5b5354174cb1256f93b6c7c4302b60f29d65653458e2e22cc13926eaf3ed56080a2e9b3e6937849414db528c9dbdb2e3c56dcf716039f21dc4e6fbec38b",
          "sha256": "bf40ca470e95df840d52f833a3bea7712411c3317658107b1ce9033e43d937a9",
          "sha1": "04b7e2482098012fcc4aa67735a154aed8332c66",
          "md5": "aa385cd4e12d4c43eace8c4635f31631"
        }
      ]
    },
    {
      "name": "releaseRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "retoast-1.6.3.aar",
          "url": "retoast-1.6.3.aar",
          "size": 15264,
          "sha512": "804aa5b5354174cb1256f93b6c7c4302b60f29d65653458e2e22cc13926eaf3ed56080a2e9b3e6937849414db528c9dbdb2e3c56dcf716039f21dc4e6fbec38b",
          "sha256": "bf40ca470e95df840d52f833a3bea7712411c3317658107b1ce9033e43d937a9",
          "sha1": "04b7e2482098012fcc4aa67735a154aed8332c66",
          "md5": "aa385cd4e12d4c43eace8c4635f31631"
        }
      ]
    }
  ]
}
