{
  "formatVersion": "1.1",
  "component": {
    "group": "github.ryuunoakaihitomi.poweract",
    "module": "poweract",
    "version": "1.4.5",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "6.7.1",
      "buildId": "n5mhucj25rfjxp3lihni3swiym"
    }
  },
  "variants": [
    {
      "name": "releaseApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "poweract-1.4.5.aar",
          "url": "poweract-1.4.5.aar",
          "size": 51328,
          "sha512": "210e68c9a1487c5eaf2c91b20e305b81e8c219b4ad9657037027c5ddacf98a488711c6d6b1a0e9edf3034a8e53b131ce11aa04ca1b7ef86a5737405d9cc1506a",
          "sha256": "e135ee5b1da4f70cedbe7783de91e27ff4b5d0cfe108c5129ff11888bd3342c4",
          "sha1": "a5cfcdb8af62f93aa573a78f73723e0b566618cd",
          "md5": "52b6e4d489cbaf370ee988a8088e6508"
        }
      ]
    },
    {
      "name": "releaseRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "poweract-1.4.5.aar",
          "url": "poweract-1.4.5.aar",
          "size": 51328,
          "sha512": "210e68c9a1487c5eaf2c91b20e305b81e8c219b4ad9657037027c5ddacf98a488711c6d6b1a0e9edf3034a8e53b131ce11aa04ca1b7ef86a5737405d9cc1506a",
          "sha256": "e135ee5b1da4f70cedbe7783de91e27ff4b5d0cfe108c5129ff11888bd3342c4",
          "sha1": "a5cfcdb8af62f93aa573a78f73723e0b566618cd",
          "md5": "52b6e4d489cbaf370ee988a8088e6508"
        }
      ]
    }
  ]
}
