{
  "formatVersion": "1.1",
  "component": {
    "group": "github.ryuunoakaihitomi.retoast",
    "module": "retoast",
    "version": "1.3.2",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "6.5",
      "buildId": "vy5e32xrnnhfpe7lrrlroclbbq"
    }
  },
  "variants": [
    {
      "name": "releaseApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "retoast-1.3.2.aar",
          "url": "retoast-1.3.2.aar",
          "size": 7414,
          "sha512": "caa387a5ade18de68745f7590f5ab92a97f6c670e3779a37cb189b7278c47b3fea8d8b3bdbe2123df0795831893caa1fafbbc0938bae8f3c3a289a18c793f456",
          "sha256": "a9799cfc2d846000d704fece62603402b71c8b378f7cd9a0db39b66831c4059f",
          "sha1": "1a5de70c83b8e625fc7c7d067f20e2ded594895d",
          "md5": "4d4e34562b8675d299609cabeef69cb4"
        }
      ]
    },
    {
      "name": "releaseRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "retoast-1.3.2.aar",
          "url": "retoast-1.3.2.aar",
          "size": 7414,
          "sha512": "caa387a5ade18de68745f7590f5ab92a97f6c670e3779a37cb189b7278c47b3fea8d8b3bdbe2123df0795831893caa1fafbbc0938bae8f3c3a289a18c793f456",
          "sha256": "a9799cfc2d846000d704fece62603402b71c8b378f7cd9a0db39b66831c4059f",
          "sha1": "1a5de70c83b8e625fc7c7d067f20e2ded594895d",
          "md5": "4d4e34562b8675d299609cabeef69cb4"
        }
      ]
    }
  ]
}
