{
  "formatVersion": "1.1",
  "component": {
    "group": "com.abdeveloper",
    "module": "multi-select-dialog-v21",
    "version": "zqy_mod_1.0.1",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.6"
    }
  },
  "variants": [
    {
      "name": "releaseVariantReleaseApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "multi-select-dialog-v21-zqy_mod_1.0.1.aar",
          "url": "multi-select-dialog-v21-zqy_mod_1.0.1.aar",
          "size": 16625,
          "sha512": "2304d535b43445e9c9de81698c91631ed02f76edc17ec1aebbf505e9daad9372c7652c8b4d8efd396e5e97ffa0af30e257f868ceb2c15f098a0972c2be4338ba",
          "sha256": "52cb1f0700dbb250e3f8a12ad09455c77ed1cd5ebf2c8e67cd2e24a55bf48757",
          "sha1": "b5182378cc34c3816b33c59e9db9d4395d7d2d89",
          "md5": "4dfb893b09699ae6c0673c69a8858176"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-bom",
          "version": {
            "requires": "1.8.22"
          },
          "attributes": {
            "org.gradle.category": "platform"
          },
          "endorseStrictVersions": true
        },
        {
          "group": "androidx.appcompat",
          "module": "appcompat",
          "version": {
            "requires": "1.7.0"
          }
        },
        {
          "group": "androidx.recyclerview",
          "module": "recyclerview",
          "version": {
            "requires": "1.3.2"
          }
        }
      ],
      "files": [
        {
          "name": "multi-select-dialog-v21-zqy_mod_1.0.1.aar",
          "url": "multi-select-dialog-v21-zqy_mod_1.0.1.aar",
          "size": 16625,
          "sha512": "2304d535b43445e9c9de81698c91631ed02f76edc17ec1aebbf505e9daad9372c7652c8b4d8efd396e5e97ffa0af30e257f868ceb2c15f098a0972c2be4338ba",
          "sha256": "52cb1f0700dbb250e3f8a12ad09455c77ed1cd5ebf2c8e67cd2e24a55bf48757",
          "sha1": "b5182378cc34c3816b33c59e9db9d4395d7d2d89",
          "md5": "4dfb893b09699ae6c0673c69a8858176"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseSourcePublication",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "multi-select-dialog-v21-zqy_mod_1.0.1-sources.jar",
          "url": "multi-select-dialog-v21-zqy_mod_1.0.1-sources.jar",
          "size": 6639,
          "sha512": "51c810fb26d766234bcf7e756c729b8b13faa6267780bacbe41afd886659e9435fb756424f071179b6c3c928d47dae9e10ce7d6b0adb511ef21b6e86649848d5",
          "sha256": "39236a77ec4d52793139f88c51314387bc734fcacc35686b69237172ee5c6676",
          "sha1": "fe912520ab3b43da96487d7afb2443ba04bf3dfd",
          "md5": "b265aa0a4e45b66cddfb45e75332ab9d"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseJavaDocPublication",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "javadoc",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "multi-select-dialog-v21-zqy_mod_1.0.1-javadoc.jar",
          "url": "multi-select-dialog-v21-zqy_mod_1.0.1-javadoc.jar",
          "size": 332987,
          "sha512": "052a489f07f1f7333f3cb27850c28b3c0b687f2201b9242e783c90d8940c66f7329876c036964abd9509e0060563a8b831440043f1a153377403525ac74c94e0",
          "sha256": "3c22a2979efd5ec7afa00d22f7860ae63893966b525f6ffaf3ee426cd16f8b66",
          "sha1": "ae8ad94a3e577529cf45b679942af89848ac2378",
          "md5": "613fb4693fe67f4191ef208883df5667"
        }
      ]
    }
  ]
}
